codebase: tg
# ALL AVAILABLE VOICES (so far)
# 'us-clb' - US Female (Nitech ARCTIC)
# 'us-slt' - US Female (Nitech ARCTIC; Midwestern)
# 'us-rms' - US Male (Nitech ARCTIC)
voices:
  # Feminine voiceset
  fem:     pl-mbrola
  # Masculine voiceset
  mas:     pl-multisyn
  # Non-AI announcements (like vox_login, etc)
  default: us-clb # Current /vg/ default
  #default: scot-awb # Scottish voice, absolutely fucking hilarious
#Plug in your own wordlists here.
phrasefiles:
  - wordlists/aq/testowy.txt
  # /vg/-specific announcements
  #- wordlists/vg/announcements.txt
  # /vg/-specific antags
  #- wordlists/vg/antags.txt
  # /vg/-specific chemistry
  #- wordlists/vg/chemistry.txt
  # /vg/-specific mining
  #- wordlists/vg/mining.txt
  # /vg/-specific miscellaneous shit
  #- wordlists/vg/misc.txt
  # /vg/-specific songs
  #- wordlists/vg/songs.txt
  # Common wordlists for all stations
  #- wordlists/common.txt
  # Censored announcements for "clean" stations.
  #- wordlists/common-clean.txt
  # Common profanity for all stations.
  #- wordlists/profanity.txt
# Here, we can override the autodetected defaults for each phrase.
overrides:
  # Silence for 0.5s (see resynth_sounds.sh)
  # We can figure out the duration ourselves, and it counts as 1 word
  '.':
    flags:
      #- old-vox
      - no-process
      - no-trim
    #duration: 0.431202
    #word-count: 1
  ',':
    flags:
      #- old-vox
      - no-process
      - no-trim
    #duration: 0.248889
    #word-count: 1
  _bloop:
    flags:
      - old-vox
      - no-process
    duration: 0.609342
    word-count: 1
  _bizwarn:
    flags:
      - old-vox
      - no-process
    duration: 0.888435
    word-count: 1
  _buzwarn:
    flags:
      - old-vox
      - no-process
    duration: 0.781224
    word-count: 1
  _doop:
    flags:
      - old-vox
      - no-process
    duration: 1.145669
    word-count: 1
  _dadeda:
    flags:
      - old-vox
      - no-process
    duration: 0.887982
    word-count: 1
  _woop:
    flags:
      - old-vox
      - no-process
    duration: 0.630295
    word-count: 1
